
# Designed and developed by Patrick Leyshock (leyshock@ohsu.edu) And Jacob Bieker (jacob@bieker.us)

# Script consolidates multiple .xls files (generated by Aperio image-analysis software) into one .xlsx workbook
#   Input to script is multiple .xls files.  There is one .xls file per slide, with one or more rows, each row
#     corresponding to a region selected in the image
#   Output is a single .xlsx worksheet
#
# Assumptions:
#   1.  script is located in same directory as input files
#   2.  directory containing input files contains only this script, plus .xls files to be consolidated
#   3.  input .xls files follow this naming convention:
#
#             mouse_NN_slide_MM_stain_MM.xls
#
#       so for mouse 3, slide 2, stain 5, the file name should be:
#
#             mouse_3_slide_2_stain_5.xls
#
#       Note that the delimitator between each component of the file name can be 
#       any of the following: ",", " ", or "_"

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Configuration
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   load appropriate libraries
library(readxl);
library(xlsx);
#library(yaml);

#   TODO:  move this to config file
predefined.column.headers <- c("Mouse ID",
                    "Slide Number",
                    "Stain Number",
                    "Region",
                    "Length (um)",
                    "Area (um2)",
                    "Text",
                    "Percent Positive Nuclei",
                    "Intensity Score",
                    "(3+) Percent Nuclei",
                    "(2+) Percent Nuclei",
                    "(1+) Percent Nuclei",
                    "(0+) Percent Nuclei",
                    "Average Positive Intensity",
                    "Average Negative Intensity",
                    "(3+) Nuclei",
                    "(2+) Nuclei",
                    "(1+) Nuclei",
                    "(0+) Nuclei",
                    "Total Nuclei",
                    "Average Nuclear RGB Intensity",
                    "Average Nuclear Size (Pixels)",
                    "Average Nuclear Size (um^2)",
                    "Area of Analysis (Pixels)",
                    "Area of Analysis (mm^2)");

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Utility functions
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   utility functions for mouse_MM_slide_NN_stain_NN.xls
get.mouse.id <- function(file.name) {
    #   remove file extension
    file.name <- strsplit(file.name, "\\.")[[1]][1];
    #   extract mouse number
    mouse.id <- strsplit(file.name, "_")[[1]][2];
    return(mouse.id);
}   #   get.mouse.id()

get.slide.num <- function(file.name)   {
    #   remove file extension
    file.name <- strsplit(file.name, "\\.")[[1]][1];
    #   extract mouse number
    print(strsplit(file.name, "_"))
    slide.num <- strsplit(file.name, "_")[[1]][4];    
    return(slide.num);    
}   #   get.slide.num()

get.stain.num <- function(file.name)   {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][1];
  #   extract stain number
  stain.num <- strsplit(file.name, "_")[[1]][6];
  return(stain.num);    
}   #   get.stain.num()
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Setup
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   identify all .xls files in the directory 
files <- list.files(getwd(), pattern = ".xls");
#   discard this file
#script.index <- which(files == "consolidator.R");
#files <- files[-script.index];

#   TODO: perform some error-checking, e.g. confirm that all files are .xls files, etc.

#   create data.frame for output
output <- data.frame();

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Read workbook contents into R
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   for all files in the directory
for(i in 1:length(files))   {
    #   get current file name
    file.name <- files[i];

    #   read in file content
    file.content <- read_excel(path=file.name,
                              sheet=1,     #   Workbook output by ImageScope always contains only one worksheet
                              col_names=TRUE);
    
    #   extract column headings, for output (and possibly QC), for the first file only
    if(i == 1)
        column.headings <- colnames(file.content);

    #   extract relevant metadata from file name
    mouse.id <- get.mouse.id(file.name);
    slide.num <- get.slide.num(file.name);
    stain.num <- get.stain.num(file.name);
    
    #   prepend metadata to file content
    file.content <- cbind(mouse.id, slide.num, stain.num, file.content);
    
    #   append file content to output data.frame
    output <- rbind(output, file.content);
}   #   for i
    
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Export results
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

colnames(output) <- predefined.column.headers;

#   convert factors to numbers
#       the double-nested "as" functions appear to be necessary; simply converting to numeric
#       causes big rounding errors
for(i in 1:length(colnames(output)))
    output[,i] <- as.numeric(output[,i]);

write.xlsx(output, file="consolidated_output.xlsx", sheetName="Consolidated files", row.names=FALSE);




