@echo off

:: A batch script for running R scripts in M$ XP
:: Just attach your R script to the end of this batch file (below the
:: last ":::" comment line) and run this script.

:: A portion of this file was taken from Gabor Grothendieck's
:: batchfiles http://cran.r-project.org/contrib/extra/batchfiles/
:: Copyright by Gabor Grothendieck 2005, GPL v2

setlocal
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: I could not get this to work on M$ 2k
ver | findstr XP >NUL
if errorlevel 1 echo Warning: This script only works on Windows XP.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:: Find R.
:: use environment variable R_HOME if defined
:: else current folder if bin\rcmd.exe exists
:: else most current R as determined by registry entry
:: else error, not found.
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
if not defined R_HOME if exist bin\rcmd.exe set R_HOME=%CD%
if not defined R_HOME for /f "tokens=2*" %%a in (
  'reg query hkcu\software\r-core\r /v InstallPath 2^>NUL ^| findstr InstallPath'
  ) do set R_HOME=%%~b
if not defined R_HOME for /f "tokens=2*" %%a in (
  'reg query hklm\software\r-core\r /v InstallPath 2^>NUL ^| findstr InstallPath'
   ) do set R_HOME=%%~b
if not defined R_HOME echo Error: R not found. Please install R (www.r-project.org). & pause & exit /b

set cmdpath=%R_HOME%\bin\R.exe
set thisfile=%~f0

:: Run R.  Make it parse the commands at the end of this file
echo x=readLines(Sys.getenv('thisfile'));eval(parse(text=x[-(1:grep('Put R code below',x)[2])]))  | "%cmdpath%" --vanilla

endlocal
exit /b

:::::::::::::::::::  Put R code below this line :::::::::::::::::::::

# Designed and developed by Patrick Leyshock (leyshock@ohsu.edu) And Jacob Bieker (jacob@bieker.us)

# Script consolidates multiple .xls files (generated by Aperio image-analysis software) into one .xlsx workbook
#   Input to script is multiple .xls files.  There is one .xls file per slide, with one or more rows, each row
#     corresponding to a region selected in the image
#   Output is a single .xlsx worksheet
#
# Assumptions:
#   1.  script is located in same directory as input files
#   2.  directory containing input files contains only this script, the master.xlsx file
#       plus .xls files to be consolidated
#   3.  Master file has the groups of the mice in numerical order
#   4.  input .xls files follow this naming convention:
#
#             mouse_NN_slide_MM_stain_MM.xls
#
#       so for mouse 3, slide 2, stain 5, the file name should be:
#
#             mouse_3_slide_2_stain_5.xls
#
#       Note that the delimitator between each component of the file name can be 
#       any of the following: "_"

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Configuration
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
# Uncomment below if the JVM is running out of heap space
# Default should be fine for most data sets, tested on > 6000 files w/o 
# using this option
# options(java.parameters = "-Xmx1024m")

# Check if libraries are installed, if not, install them
if(require("XLConnect") & require("yaml")){
  print("XLConnect, yaml are loaded correctly")
} else {
  print("trying to install XLConnect, yaml")
  install.packages("XLConnect")
  install.packages("yaml")
  if(require("XLConnect") & require("yaml")){
    print("XLConnect, yaml are installed and loaded")
  } else {
    stop("could not install XLConnect, yaml")
  }
}

#   load appropriate libraries
library(readxl);
library(XLConnect);
library(yaml);

#loads column names from config file config.yml
predefined.column.headers <- yaml.load_file("config.yml");

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Utility functions
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   utility functions for mouse_MM_slide_NN_stain_NN.xls
get.mouse.id <- function(file.name) {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][1];
  #   extract mouse number
  mouse.id <- strsplit(file.name, "_")[[1]][2];
  return(mouse.id);
}   #   get.mouse.id()

get.slide.num <- function(file.name)   {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][1];
  #   extract mouse number
  slide.num <- strsplit(file.name, "_")[[1]][4];    
  return(slide.num);    
}   #   get.slide.num()

get.stain.name <- function(file.name)   {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][1];
  #   extract stain number
  stain.name <- strsplit(file.name, "_")[[1]][6];
  #Checks if stain name does not exist, because the output will be messed up if so
  if (is.na(stain.name)) {
    noStainError <- paste0("Warning: File ", file.name, " does not conform to the naming convention
                           , please rename file and rerun script")
    stop(noStainError)
  }
  return(stain.name);
}   #   get.stain.name()
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Setup
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#Remove older consolidated_files file
fn <- "consolidated_files.xlsx";
if(file.exists(fn))
  file.remove(fn);

#   identify all .xls files in the directory 
files <- list.files(getwd(), pattern = ".xls$");

# remove master file with groups from list of files vector
files <- setdiff(files, "master.xls");

#   load master workbook so that know which groups Mice are in
masterwkbk <- loadWorkbook("master.xlsx", create = FALSE)

#   create list to hold output data.frames
output <- list();
#   create vector for storing the different stain numbers so that diff sheets created
stain.names <- c();
#   create workbook to save the data to
workbook <- loadWorkbook("consolidated_files.xlsx", create = TRUE);
#   create vector to store the different mice id for use in the summary
mouse.ids <- c();

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#  Get data from master file
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   read in file content
master.workbook <- loadWorkbook("master.xlsx")
master.content <- readWorksheet(master.workbook, sheet = 1)
# Get vector of genotypes in numerical order to apply later
master.genotype <- master.content$Genotype


#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Read workbook contents into R
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   for all files in the directory
for(i in 1:length(files))   {
  
  #   get current file name
  file.name <- files[i];
  
  #   read in file content
  file.workbook <- loadWorkbook(file.name);
  file.content <- readWorksheet(file.workbook, sheet = 1);
  
  #   extract column headings, for output (and possibly QC), for the first file only
  if(i == 1)
    column.headings <- colnames(file.content);
  
  #   extract relevant metadata from file name
  mouse.idnum <- get.mouse.id(file.name);
  slide.number <- get.slide.num(file.name);
  stain.number <- get.stain.name(file.name);
  #Convert to numeric right after getting number
  mouse.idnum <- as.numeric(mouse.idnum)
  slide.number <- as.numeric(slide.number)
  mouse.group <-  master.genotype[as.numeric(mouse.idnum)]
  #Adds stain number to stain.names if it does not already exist in the vector
  if(!stain.number %in% stain.names) {
    stain.names <- c(stain.names, stain.number);
    #  Create a sheet in the master workbook for each stain
    createSheet(workbook, name = stain.number);
  }
  
  #Adds stain number to stain.names if it does not already exist in the vector
  if(!mouse.idnum %in% mouse.ids) {
    mouse.ids <- c(mouse.ids, mouse.idnum);
  }
  
  #   prepend metadata to file content
  file.content <- cbind(mouse.group, stain.number,mouse.idnum, slide.number, file.content);
  
  #   append file content to output data.frame
  output <- rbind(output, file.content);
  
  
}   #   for i

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Export results
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------


#Assign the column names to the data.frame
colnames(output) <- predefined.column.headers;

#Subset output so that Stain Num are not converted and stay strings
#Then add back in to data.frame 
factor_to_numbers <- output
factor_to_numbers$'Stain' <- NULL
factor_to_numbers$'Group' <- NULL

#   convert factors to numbers
#       Not elegant, but needed so that the first three columns are converted
#       to their numeric values and not factor level values
factor_to_numbers<- sapply(factor_to_numbers, function(x) if(is.factor(x)) {
  as.numeric(as.character(x));
} else {
  as.numeric(x);
})

factor_to_numbers <- data.frame(factor_to_numbers)
#Reassign stain back to the temp data.frame
factor_to_numbers$'Stain' <- output$'Stain'
factor_to_numbers$'Group' <- output$'Group'
#Output is then given the modified data.frame for use in the rest of the script
output <- factor_to_numbers
#Reorder so that Stain and Group are the first two columns, like it was originally
output <- output[c(length(output), length(output) - 1, seq(1, length(output) - 2, by = 1))]

#Reassign column names lost in above step
colnames(output) <- predefined.column.headers;

#Convert to numeric
mouse.ids <- as.numeric(mouse.ids);

#Order the output by the Group
output <- output[with(output, order(Group)),]

#  get the current sheets in the master workbook, which is in the same order
#  as stain.number
currentSheets <- getSheets(workbook);

for(i in 1:length(currentSheets)) {
  # Selects the subset of the output that has the same stain number
  output.subset <- output[output[,2]==stain.names[i],]
  #Drops the Stain number from the data.frame before writing it
  output.subset[,2] <- NULL
  #Get rid of stain number on columns, since that is stored in sheet name
  writeWorksheet(workbook, output.subset, sheet = currentSheets[i], 1, 1, header = TRUE)
}

#saves and actually writes the data to an Excel file
saveWorkbook(workbook);


#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Summary of Data
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------


#Create the sheet for the summary
createSheet(workbook, name = "summary");

#Write the data of the summary run in the top left corner
writeWorksheet(workbook, date(), sheet = "summary", header = FALSE);

#create summary data.frame to put all the summary info into
mouse.summary.output <- data.frame();

#subset data for each mouse and perform calulations on it
for(i in 1:length(mouse.ids)) {
  #vector to store the data before putting into summary output
  current.summary <- NULL;
  #Add the mouse ID to the current.summary
  current.summary <- c(current.summary, mouse.ids[i])
  for(j in 1:length(stain.names)) {
    #subset output for current mouse and stain numbers
    mouse.data.current <- subset(output, output[,3]==mouse.ids[i] & output[,2]==stain.names[j])
    #Perform the calculations
    #   Averaging to get the number of cells per mm per stain and mouse
    average.size <- mean(mouse.data.current[,26]);
    #   First 3+ 2+ and 1+ average
    average.cells321 <- mean(mouse.data.current[,17]+mouse.data.current[,18]+mouse.data.current[,19]);
    average.321cellpermm <- average.cells321/average.size;
    #   Then 3+ 2+ average
    average.cells32 <- mean(mouse.data.current[,17]+mouse.data.current[,18]);
    average.32cellpermm <- average.cells32/average.size;
    #   Last 3+ average
    average.cells3 <- mean(mouse.data.current[,17]);
    average.3cellpermm <- average.cells3/average.size;
    #Append average cell to current summary
    current.summary <- c(current.summary, average.321cellpermm, average.32cellpermm, average.3cellpermm);
  }
  #End of inside for loop
  #save the current.summary to overall summary
  mouse.summary.output <- rbind(mouse.summary.output, current.summary)
}

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Formatting Excel Document
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#  Create CellStyles to use later
average.header <- createCellStyle(workbook, name = "AvgHeader")

#Set foreground color for average.header
setFillPattern(average.header, XLC$FILL.SOLID_FOREGROUND)
setFillForegroundColor(average.header, XLC$COLOR.TURQUOISE)
#setBorder(average.header, side = "all", XLC$BORDER.MEDIUM, color = XLC$COLOR.BLACK)

#    Create header for above the stain numbers
#have reference to get correct number of columns
reference <- paste0("C3:", LETTERS[(3 * length(stain.names))+2], "3")
mergeCells(workbook, sheet = "summary", reference)
mergedCellsIndex <- seq(2, length(stain.names)+1, 1)

#Write to the worksheet
writeWorksheet(workbook, "Average Cells/mm Per Stain for (3+, 2+, 1+), (3+, 2+), and (3+)", sheet = "summary", 3, 3, header = FALSE)
#Set CellStyle to average.header
setCellStyle(workbook, sheet = "summary", row = 3, col = mergedCellsIndex+1, cellstyle = average.header)

#Create the columns for the data to go in
summary.col.names <- c();

for(i in 1:length(stain.names)) {
  stain.name <- paste0("Stain ", as.character(stain.names[i]));
  #put in the initial names
  if(i==1){
    summary.col.names <- c("Mouse ID", stain.name);
  } else {
    # Very hack-y method at the moment
    summary.col.names <- c(summary.col.names, "NA", "NA", stain.name);
  }
}

# Make stain names span 3 columns so that the different averages can be included below
#  Create CellStyles to use later
stain.header <- createCellStyle(workbook, name = "StainHeader")

#Create the columns for the data to go in
summary.stain.names <- c();
#Index to track where to put the next header
index <- 0

for(i in 1:length(stain.names)) {
  stain.name <- paste0("Stain ", as.character(stain.names[i]));
  #    Create header for above the stain numbers
  #have reference to get correct number of columns
  # TODO add support for if the stains go into the double letter range
  if (i == 1) {
    mergeCells(workbook, sheet = "summary", "C4:E4")
  } else {
  reference <- paste0(LETTERS[index+3],"4:", LETTERS[index+5], "4")
  mergeCells(workbook, sheet = "summary", reference)
}
  #Write to the worksheet
  writeWorksheet(workbook, stain.name, sheet = "summary", 4, 2, header = FALSE)
  #up index by three since each stain takes up three columns
  index <- index + 3
}

#Apply column names to the summary output
colnames(mouse.summary.output) <- summary.col.names

writeWorksheet(workbook, mouse.summary.output, sheet = "summary", startRow = 4, startCol = 2)

# Add groups to summary sheet, adding it to mouse.summary.output changed all numerics to characters
group.names <- c();
mice.ids <- mouse.summary.output$`Mouse ID`
for(i in 1:length(mice.ids)) {
  current.data <- subset(output, output[,3]==mice.ids[i])
  current.data.row <- head(current.data, 1)
  # Taken from: https://stackoverflow.com/questions/24447877/invalid-factor-level-na-generated-when-pasting-in-a-dataframe-in-r
  current.data.row[,c(1)] <- sapply(current.data.row[,c(1)],as.character) 
  #Adds name to the vector
  group.names <- c(group.names, current.data.row$Group)
}
#Converts to data.frame starting with data.frame resulted in NA errors
group.names <- as.data.frame(group.names)

colnames(group.names) <- "Group"

writeWorksheet(workbook, group.names, sheet = "summary", startRow = 4)
#Save to workbook after creating the summary
saveWorkbook(workbook)