columnHeaders: 
- col1: "Mouse ID"
- col2: "Slide Number"
- col3: "Region"
- col4: "Length (um)"
- col5: "Area (um2)"
- col6: "Text"
- col7: "Percent Positive Nuclei"
- col8: "Intensity Score"
- col9: "(3+) Percent Nuclei"
- col10: "(2+) Percent Nuclei"
- col11: "(1+) Percent Nuclei"
- col12: "(0+) Percent Nuclei"
- col13: "Average Positive Intensity"
- col14: "Average Negative Intensity"
- col15: "(3+) Nuclei"
- col16: "(2+) Nuclei"
- col17: "(1+) Nuclei"
- col18: "(0+) Nuclei"
- col19: "Total Nuclei"
- col20: "Average Nuclear RGB Intensity"
- col21: "Average Nuclear Size (Pixels)"
- col22: "Average Nuclear Size (um^2)"
- col23: "Area of Analysis (Pixels)"
- col24: "Area of Analysis (mm^2)"