#Config file for consolidator.R To change the column names in the Excel file
#Change the names here
- "Stain Num"
- "Mouse ID"
- "Slide Number"
- "Region"
- "Length (um)"
- "Area (um2)"
- "Text"
- "Percent Positive Nuclei"
- "Intensity Score"
- "(3+) Percent Nuclei"
- "(2+) Percent Nuclei"
- "(1+) Percent Nuclei"
- "(0+) Percent Nuclei"
- "Average Positive Intensity"
- "Average Negative Intensity"
- "(3+) Nuclei"
- "(2+) Nuclei"
- "(1+) Nuclei"
- "(0+) Nuclei"
- "Total Nuclei"
- "Average Nuclear RGB Intensity"
- "Average Nuclear Size (Pixels)"
- "Average Nuclear Size (um^2)"
- "Area of Analysis (Pixels)"
- "Area of Analysis (mm^2)"