
# Designed and developed by Patrick Leyshock (leyshock@ohsu.edu) And Jacob Bieker (jacob@bieker.us)

# Script consolidates multiple .xls files (generated by Aperio image-analysis software) into one .xlsx workbook
#   Input to script is multiple .xls files.  There is one .xls file per slide, with one or more rows, each row
#     corresponding to a region selected in the image
#   Output is a single .xlsx worksheet
#
# Assumptions:
#   1.  script is located in same directory as input files
#   2.  directory containing input files contains only this script, plus .xls files to be consolidated
#   3.  input .xls files follow this naming convention:
#
#             mouse_NN_slide_MM_stain_MM.xls
#
#       so for mouse 3, slide 2, stain 5, the file name should be:
#
#             mouse_3_slide_2_stain_5.xls
#
#       Note that the delimitator between each component of the file name can be 
#       any of the following: "_"

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Configuration
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   load appropriate libraries
library(readxl);
library(XLConnect);
library(yaml);

#loads column names from config file config.yml
predefined.column.headers <- yaml.load_file("config.yml");

#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Utility functions
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   utility functions for mouse_MM_slide_NN_stain_NN.xls
get.mouse.id <- function(file.name) {
    #   remove file extension
    file.name <- strsplit(file.name, "\\.")[[1]][1];
    #   extract mouse number
    mouse.id <- strsplit(file.name, "_")[[1]][2];
    return(mouse.id);
}   #   get.mouse.id()

get.slide.num <- function(file.name)   {
    #   remove file extension
    file.name <- strsplit(file.name, "\\.")[[1]][1];
    #   extract mouse number
    slide.num <- strsplit(file.name, "_")[[1]][4];    
    return(slide.num);    
}   #   get.slide.num()

get.stain.num <- function(file.name)   {
  #   remove file extension
  file.name <- strsplit(file.name, "\\.")[[1]][1];
  #   extract stain number
  stain.num <- strsplit(file.name, "_")[[1]][6];
  return(stain.num);    
}   #   get.stain.num()
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Setup
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#Remove previous xlsx files, JUST FOR TESTING
fn <- "consolidated_files.xlsx";
if(file.exists(fn))
  file.remove(fn);

#   identify all .xls files in the directory 
files <- list.files(getwd(), pattern = ".xls");

#   TODO: perform some error-checking, e.g. confirm that all files are .xls files, etc.

#   create list to hold output data.frames
output <- list();
#   create vector for storing the different stain numbers so that diff sheets created
stain.numbers <- c();
#   create workbook to save the data to
workbook <- loadWorkbook("consolidated_files.xlsx", create = TRUE);
#   create vector to store the different mice id for use in the summary
mouse.ids <- c();
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Read workbook contents into R
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   for all files in the directory
for(i in 1:length(files))   {

    #   get current file name
    file.name <- files[i];

    #   read in file content
    file.content <- read_excel(path=file.name,
                              sheet=1,     #   Workbook output by ImageScope always contains only one worksheet
                              col_names=TRUE);
    
    #   extract column headings, for output (and possibly QC), for the first file only
    if(i == 1)
        column.headings <- colnames(file.content);

    #   extract relevant metadata from file name
    mouse.idnum <- get.mouse.id(file.name);
    slide.number <- get.slide.num(file.name);
    stain.number <- get.stain.num(file.name);
    
    #Adds stain number to stain.numbers if it does not already exist in the vector
    if(!stain.number %in% stain.numbers) {
      stain.numbers <- c(stain.numbers, stain.number);
      #  Create a sheet in the master workbook for each stain
      createSheet(workbook, name = stain.number);
    }
    
    #Adds stain number to stain.numbers if it does not already exist in the vector
    if(!mouse.idnum %in% mouse.ids) {
      mouse.ids <- c(mouse.ids, mouse.idnum);
    }
    
    #   prepend metadata to file content
    file.content <- cbind(stain.number,mouse.idnum, slide.number, file.content);
    
    #   append file content to output data.frame
    output <- rbind(output, file.content);
    
    
}   #   for i
    
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Export results
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------


#Assign the column names to the data.frame
colnames(output) <- predefined.column.headers;




#  get the current sheets in the master workbook, which is in the same order
#  as stain.number
currentSheets <- getSheets(workbook);

#TODO Use the list of names from the config file to choose dataframe columns
#Instead of hardcoding it in

for(i in 1:length(currentSheets)) {
  # Selects the subset of the output that has the same stain number
  output.subset <- output[output$`Stain Num`==stain.numbers[i],]
  #Drops the Stain number from the data.frame before writing it
  output.subset$`Stain Num` <- NULL
  #Get rid of stain number on columns, since that is stored in sheet name
  writeWorksheet(workbook, output.subset, sheet = currentSheets[i], 1, 1, header = TRUE)
}

#saves and actually writes the data to an Excel file
saveWorkbook(workbook);


#-------------------------------------------------------------------------
#-------------------------------------------------------------------------
#   Summary of Data
#-------------------------------------------------------------------------
#-------------------------------------------------------------------------

#   convert factors to numbers
#       Not elegant, but needed so that the first three columns are converted
#       to their numeric values and not factor level values
output<- sapply(output, function(x) if(is.factor(x)) {
  as.numeric(as.character(x));
} else {
  as.numeric(x);
})
output <- data.frame(output);

#Reassign column names lost in above step
colnames(output) <- predefined.column.headers;

#Convert to numeric
mouse.ids <- as.numeric(mouse.ids);
stain.numbers <- as.numeric(stain.numbers);

#Create the sheet for the summary
createSheet(workbook, name = "summary");

#Write the data of the summary run in the top left corner
writeWorksheet(workbook, date(), sheet = "summary", header = FALSE);

#create summary data.frame to put all the summary info into
mouse.summary.output <- data.frame();

#subset data for each mouse and perform calulations on it
for(i in 1:length(mouse.ids)) {
  #vector to store the data before putting into summary output
  current.summary <- c();
  #Add the mouse ID to the current.summary
  current.summary <- c(current.summary, mouse.ids[i])
  for(i in 1:length(stain.numbers)) {
    #subset output for current mouse and stain numbers
    mouse.data.current <- subset(output, output$`Mouse ID`==mouse.ids[i] & output$`Stain Num`==stain.numbers[i])
    #Append mouse ID to the summary
    #check if the stain for the mouse data exists
    if(stain.numbers[i] %in% mouse.data.current$`Stain Num`) {
      #Perform the calculations
      #   Averaging to get the number of cells per mm per stain and mouse
      average.size <- mean(mouse.data.current$`Area of Analysis (mm^2)`);
      average.cells <- mean(mouse.data.current$`Total Nuclei`);
      average.cellpermm <- average.cells/average.size;
      #Append average cell to current summary
      current.summary <- c(current.summary, average.cellpermm)
    } else {
      #Put in 0 for NA values for now
      current.summary <- c(current.summary, 0)
      print(str(current.summary))
    }
    
  }
  #End of inside for loop
  #save the current.summary to overall summary
  mouse.summary.output <- rbind(mouse.summary.output, current.summary)
}

#Create the columns for the data to go in
summary.col.names <- c();
for(i in 1:length(stain.numbers)) {
  #put in the initial names
  if(i==1){
    summary.col.names <- c("Mouse ID", as.character(stain.numbers[i]))
  } else {
    summary.col.names <- c(summary.col.names, as.character(stain.numbers[i]))
  }
}

#Apply column names to the summary output
colnames(mouse.summary.output) <- summary.col.names



#Save to workbook after creating the summary
saveWorkbook(workbook)